services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rpa-web
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - rpa-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: rpa-sql
    environment:
      SA_PASSWORD: "SuaSenha123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - rpa-network

networks:
  rpa-network:
    driver: bridge
